<a href="https://colab.research.google.com/github/JoshEthan/Prove06/blob/master/07Prove_Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Instructions

* Use a library implementation to make predictions on several different datasets
* Make predictions on at least **four** different datasets.
* Among your datasets make sure that you worked with the following characteristics:
    * Text values
    * Binary classification (only two possible values)
    * Classification with more than two target values
    * Regression (numeric target values)
    * Look at different measures of success for your datasets (more than just accuracy)

# Data Set 1 - League of Legends

In [0]:
#LOAD DATA
import pandas as pd
pd.set_option('display.max_columns', 500)
data = pd.read_csv("/content/high_diamond_ranked_10min.csv")


#SPLIT INTO X AND Y
X = data.drop(columns=["gameId", "blueWins"]).astype('int32').to_numpy()
y = data.blueWins.to_numpy()


#NORMALIZE
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

#TRAINING AND TESTING SET
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)


#### BUILDING THE MODEL ###
import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()    # Specifies we are creating model sequentially 
                        #   and the each output layer is input to the next layer.

# ADD EACH LAYER
model.add(Dense(20, input_dim=38, activation='relu'))    # 'model.add' add a layer to our neural network.
                                                        #   'Dense' specify fully connected layer.
                                                        #       Arguments: Output(16), Input(20), Activation Function(relu)
model.add(Dense(1, activation='sigmoid')) # X layer we dont need to specify input(16), the model to be sequential


# LOSS FUNCTION/OPTIMIZER
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])   # 'Categorical_crossentropy' multiple classes.
                                                                                    # Metrics is used to specify 
                                                                                    #   the way to judge the performance.
                                                                                    # 'loss' what to use to evaluate a set of weights
                                                                                    # 'optimizer' is used to search through different weights
                                                                                    # “adam“ stochastic gradient descent algorithm 
                                                                                    # 'accuracy' because it is a classification problem



# LOSS FUNCTION/OPTIMIZER
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])   # 'Categorical_crossentropy' multiple classes.
                                                                                    # Metrics is used to specify 
                                                                                    #   the way to judge the performance.
                                                                                    # 'loss' what to use to evaluate a set of weights
                                                                                    # 'optimizer' is used to search through different weights
                                                                                    # “adam“ stochastic gradient descent algorithm 
                                                                                    # 'accuracy' because it is a classification problem






#TRAINING
history = model.fit(X_train, y_train, epochs=100, batch_size=100)    # Specify: 
                                                                    #   input data-> X_train, 
                                                                    #   labels-> y_train, 
                                                                    #   number of epochs(iterations), 
                                                                    #   and batch size. 
                                                                    # Returns history of model training.
                                                                    # Batch Size: 
                                                                    #   Divides data into batches = batch_size. 
                                                                    #   Only this number of samples will be loaded/processed. 
                                                                    #   Once we are done with one batch, next batch will be processed.
                                                                    # Epoch: One pass through all of the rows in the training dataset.
                                                                    #   One epoch is comprised of one or more batches


#Use your network to make predictions about a test set and note the success of the algorithm on your dataset.

#Experiment with at least 3 different sets of hyper-parameters for the algorithm 
#   (e.g., different number of layers and nodes per layer, different learning rates, different activation functions, etc.).

# check the model’s performance
_, accuracy = model.evaluate(X, y, verbose=0)
print('Accuracy: %.2f' % (accuracy*100))


Epoch 1/100
8891/8891 [==============================] - 0s 21us/step - loss: 0.6561 - accuracy: 0.6357
Epoch 2/100
8891/8891 [==============================] - 0s 12us/step - loss: 0.5499 - accuracy: 0.7156
Epoch 3/100
8891/8891 [==============================] - 0s 13us/step - loss: 0.5407 - accuracy: 0.7204
Epoch 4/100
8891/8891 [==============================] - 0s 13us/step - loss: 0.5358 - accuracy: 0.7224
Epoch 5/100
8891/8891 [==============================] - 0s 12us/step - loss: 0.5326 - accuracy: 0.7267
Epoch 6/100
8891/8891 [==============================] - 0s 13us/step - loss: 0.5307 - accuracy: 0.7268
Epoch 7/100
8891/8891 [==============================] - 0s 12us/step - loss: 0.5290 - accuracy: 0.7296
Epoch 8/100
8891/8891 [==============================] - 0s 13us/step - loss: 0.5275 - accuracy: 0.7301
Epoch 9/100
8891/8891 [==============================] - 0s 12us/step - loss: 0.5267 - accuracy: 0.7306
Epoch 10/100
8891/8891 [==============================] - 0s 13u

# Data Set 2 - Spotify

In [0]:
#LOAD DATA
import pandas as pd
pd.set_option('display.max_columns', 500)
data = pd.read_csv("/content/data.csv")

#SPLIT INTO X AND Y
X = data.drop(columns=["artists", "id", "name", "release_date", "popularity"]).astype('int32').to_numpy()
y = data.popularity.to_numpy()

#NORMALIZE
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

#TRAINING AND TESTING SET
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = .1)

#### BUILDING THE MODEL ###
import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()    # Specifies we are creating model sequentially 
                        #   and the each output layer is input to the next layer.

# ADD EACH LAYER
model.add(Dense(100, input_dim=15, activation='relu'))    # 'model.add' add a layer to our neural network.
                                                        #   'Dense' specify fully connected layer.
                                                        #       Arguments: Output(16), Input(20), Activation Function(relu)
model.add(Dense(1, activation='sigmoid')) # X layer we dont need to specify input(16), the model to be sequential


# LOSS FUNCTION/OPTIMIZER
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])   # 'Categorical_crossentropy' multiple classes.
                                                                                    # Metrics is used to specify 
                                                                                    #   the way to judge the performance.
                                                                                    # 'loss' what to use to evaluate a set of weights
                                                                                    # 'optimizer' is used to search through different weights
                                                                                    # “adam“ stochastic gradient descent algorithm 
                                                                                    # 'accuracy' because it is a classification problem






#TRAINING
history = model.fit(X_train, y_train, epochs=100, batch_size=10000)    # Specify: 
                                                                    #   input data-> X_train, 
                                                                    #   labels-> y_train, 
                                                                    #   number of epochs(iterations), 
                                                                    #   and batch size. 
                                                                    # Returns history of model training.
                                                                    # Batch Size: 
                                                                    #   Divides data into batches = batch_size. 
                                                                    #   Only this number of samples will be loaded/processed. 
                                                                    #   Once we are done with one batch, next batch will be processed.
                                                                    # Epoch: One pass through all of the rows in the training dataset.
                                                                    #   One epoch is comprised of one or more batches


#Use your network to make predictions about a test set and note the success of the algorithm on your dataset.

#Experiment with at least 3 different sets of hyper-parameters for the algorithm 
#   (e.g., different number of layers and nodes per layer, different learning rates, different activation functions, etc.).

# check the model’s performance
_, accuracy = model.evaluate(X, y, verbose=0)
print('Accuracy: %.2f' % (accuracy*100))


Epoch 1/100
151732/151732 [==============================] - 0s 2us/step - loss: 1423.7063 - accuracy: 0.0688
Epoch 2/100
151732/151732 [==============================] - 0s 1us/step - loss: 1415.4594 - accuracy: 0.0289
Epoch 3/100
151732/151732 [==============================] - 0s 1us/step - loss: 1409.2335 - accuracy: 0.0144
Epoch 4/100
151732/151732 [==============================] - 0s 2us/step - loss: 1405.1199 - accuracy: 0.0142
Epoch 5/100
151732/151732 [==============================] - 0s 2us/step - loss: 1402.4752 - accuracy: 0.0142
Epoch 6/100
151732/151732 [==============================] - 0s 1us/step - loss: 1400.7544 - accuracy: 0.0142
Epoch 7/100
151732/151732 [==============================] - 0s 2us/step - loss: 1399.6191 - accuracy: 0.0142
Epoch 8/100
151732/151732 [==============================] - 0s 2us/step - loss: 1398.8478 - accuracy: 0.0142
Epoch 9/100
151732/151732 [==============================] - 0s 2us/step - loss: 1398.3115 - accuracy: 0.0142
Epoch 10/1

# Data Set 3 - Movies

In [0]:
#LOAD DATA
import pandas as pd
pd.set_option('display.max_columns', 500)
data = pd.read_csv("/content/MoviesOnStreamingPlatforms_updated.csv")
data.Age = data.Age.astype('category')
data.Age = data.Age.cat.codes
data["Rotten Tomatoes"] = data["Rotten Tomatoes"].astype('category')
data["Rotten Tomatoes"] = data["Rotten Tomatoes"].cat.codes
data.Language = data.Language.astype('category')
data.Language = data.Language.cat.codes

from numpy import nan
data.dropna(inplace=True)
print(data)


#SPLIT INTO X AND 
X = data.drop(columns=["Title", "ID", "IMDb", "Directors", "Genres", "Country"]).astype('int32').to_numpy()
y = data.IMDb.to_numpy()

#NORMALIZE
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

#TRAINING AND TESTING SET
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = .1)

#### BUILDING THE MODEL ###
import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()    # Specifies we are creating model sequentially 
                        #   and the each output layer is input to the next layer.

# ADD EACH LAYER
model.add(Dense(11, input_dim=11, activation='relu'))    # 'model.add' add a layer to our neural network.
                                                        #   'Dense' specify fully connected layer.
                                                        #       Arguments: Output(16), Input(20), Activation Function(relu)
model.add(Dense(1, activation='sigmoid')) # X layer we dont need to specify input(16), the model to be sequential


# LOSS FUNCTION/OPTIMIZER
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])   # 'Categorical_crossentropy' multiple classes.
                                                                                    # Metrics is used to specify 
                                                                                    #   the way to judge the performance.
                                                                                    # 'loss' what to use to evaluate a set of weights
                                                                                    # 'optimizer' is used to search through different weights
                                                                                    # “adam“ stochastic gradient descent algorithm 
                                                                                    # 'accuracy' because it is a classification problem






#TRAINING
history = model.fit(X_train, y_train, epochs=100, batch_size=10000)    # Specify: 
                                                                    #   input data-> X_train, 
                                                                    #   labels-> y_train, 
                                                                    #   number of epochs(iterations), 
                                                                    #   and batch size. 
                                                                    # Returns history of model training.
                                                                    # Batch Size: 
                                                                    #   Divides data into batches = batch_size. 
                                                                    #   Only this number of samples will be loaded/processed. 
                                                                    #   Once we are done with one batch, next batch will be processed.
                                                                    # Epoch: One pass through all of the rows in the training dataset.
                                                                    #   One epoch is comprised of one or more batches


#Use your network to make predictions about a test set and note the success of the algorithm on your dataset.

#Experiment with at least 3 different sets of hyper-parameters for the algorithm 
#   (e.g., different number of layers and nodes per layer, different learning rates, different activation functions, etc.).

# check the model’s performance
_, accuracy = model.evaluate(X, y, verbose=0)
print('Accuracy: %.2f' % (accuracy*100))


       Unnamed: 0     ID                           Title  Year  Age  IMDb  \
0               0      1                       Inception  2010    0   8.8   
1               1      2                      The Matrix  1999    2   8.7   
2               2      3          Avengers: Infinity War  2018    0   8.5   
3               3      4              Back to the Future  1985    3   8.5   
4               4      5  The Good, the Bad and the Ugly  1966    2   8.8   
...           ...    ...                             ...   ...  ...   ...   
16734       16734  16735        Sultan And The Rock Star  1980   -1   5.9   
16737       16737  16738                 The Bears and I  1974    4   6.2   
16738       16738  16739    Whispers: An Elephant's Tale  2000    4   5.0   
16739       16739  16740       The Ghosts of Buxley Hall  1980   -1   6.2   
16740       16740  16741                  The Poof Point  2001    3   4.7   

       Rotten Tomatoes  Netflix  Hulu  Prime Video  Disney+  Type  \
0     

# Data Set 4 - Malnutrition

In [0]:
#LOAD DATA
import pandas as pd
pd.set_option('display.max_columns', 500)
data = pd.read_csv("/content/country-wise-average.csv")

from numpy import nan
data.dropna(inplace=True)

#SPLIT INTO X AND Y
X = data.drop(columns=["Income Classification", "Country"]).astype('int32').to_numpy()
y = data["Income Classification"].to_numpy()

#NORMALIZE
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

#TRAINING AND TESTING SET
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = .1)

#### BUILDING THE MODEL ###
import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()    # Specifies we are creating model sequentially 
                        #   and the each output layer is input to the next layer.

# ADD EACH LAYER
model.add(Dense(6, input_dim=6, activation='relu'))    # 'model.add' add a layer to our neural network.
                                                        #   'Dense' specify fully connected layer.
                                                        #       Arguments: Output(16), Input(20), Activation Function(relu)
model.add(Dense(1, activation='sigmoid')) # X layer we dont need to specify input(16), the model to be sequential


# LOSS FUNCTION/OPTIMIZER
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])   # 'Categorical_crossentropy' multiple classes.
                                                                                    # Metrics is used to specify 
                                                                                    #   the way to judge the performance.
                                                                                    # 'loss' what to use to evaluate a set of weights
                                                                                    # 'optimizer' is used to search through different weights
                                                                                    # “adam“ stochastic gradient descent algorithm 
                                                                                    # 'accuracy' because it is a classification problem






#TRAINING
history = model.fit(X_train, y_train, epochs=100, batch_size=10000)    # Specify: 
                                                                    #   input data-> X_train, 
                                                                    #   labels-> y_train, 
                                                                    #   number of epochs(iterations), 
                                                                    #   and batch size. 
                                                                    # Returns history of model training.
                                                                    # Batch Size: 
                                                                    #   Divides data into batches = batch_size. 
                                                                    #   Only this number of samples will be loaded/processed. 
                                                                    #   Once we are done with one batch, next batch will be processed.
                                                                    # Epoch: One pass through all of the rows in the training dataset.
                                                                    #   One epoch is comprised of one or more batches


#Use your network to make predictions about a test set and note the success of the algorithm on your dataset.

#Experiment with at least 3 different sets of hyper-parameters for the algorithm 
#   (e.g., different number of layers and nodes per layer, different learning rates, different activation functions, etc.).

# check the model’s performance
_, accuracy = model.evaluate(X, y, verbose=0)
print('Accuracy: %.2f' % (accuracy*100))


Epoch 1/100
126/126 [==============================] - 0s 439us/step - loss: 1.8343 - accuracy: 0.1667
Epoch 2/100
126/126 [==============================] - 0s 16us/step - loss: 1.8320 - accuracy: 0.1667
Epoch 3/100
126/126 [==============================] - 0s 15us/step - loss: 1.8293 - accuracy: 0.1667
Epoch 4/100
126/126 [==============================] - 0s 23us/step - loss: 1.8264 - accuracy: 0.1667
Epoch 5/100
126/126 [==============================] - 0s 15us/step - loss: 1.8235 - accuracy: 0.1746
Epoch 6/100
126/126 [==============================] - 0s 17us/step - loss: 1.8205 - accuracy: 0.1746
Epoch 7/100
126/126 [==============================] - 0s 16us/step - loss: 1.8175 - accuracy: 0.1746
Epoch 8/100
126/126 [==============================] - 0s 17us/step - loss: 1.8144 - accuracy: 0.1746
Epoch 9/100
126/126 [==============================] - 0s 20us/step - loss: 1.8114 - accuracy: 0.1746
Epoch 10/100
126/126 [==============================] - 0s 12us/step - loss: 1.80

# Text Data

In [0]:
# Once the Tokenizer has been fit on training data 
#   it can be used to encode documents in the train or test datasets.
# binary: Whether or not each word is present 
# count: Count of each word.
# tfidf: scoring for each word.

from keras.preprocessing.text import Tokenizer
# define 5 documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!']
# create the tokenizer
t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(docs)
# summarize what was learned
print(t.word_counts)
print(t.document_count)
print(t.word_index)
print(t.word_docs)
# integer encode documents
b = t.texts_to_matrix(docs, mode='binary')
c = t.texts_to_matrix(docs, mode='count')
t = t.texts_to_matrix(docs, mode='tfidf')
print(b)
print()
print(c)
print()
print(t)

OrderedDict([('well', 1), ('done', 1), ('good', 1), ('work', 2), ('great', 1), ('effort', 1), ('nice', 1), ('excellent', 1)])
5
{'work': 1, 'well': 2, 'done': 3, 'good': 4, 'great': 5, 'effort': 6, 'nice': 7, 'excellent': 8}
defaultdict(<class 'int'>, {'well': 1, 'done': 1, 'good': 1, 'work': 2, 'effort': 1, 'great': 1, 'nice': 1, 'excellent': 1})
[[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]

[[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]

[[0.         0.         1.25276297 1.25276297 0.         0.
  0.         0.         0.        ]
 [0.         0.98082925 0.         0.         1.25276297 0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         1.25276297
  1.25276297 0.         0.        ]
 [0.         0.98082925 0.         0.         0.  